name = "backend"
compatibility_date = "2024-07-29"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYThlMzQ2MGMtY2FjNS00MDU1LTk5MmQtYThkNWExMzM4MzJmIiwidGVuYW50X2lkIjoiZGRhMTllMTA1OGM3OWNhZDY3YWIzNzA1NmNjNTg5MTIzYjQ4NDUwZGI3OTYzNDQzNWRhMWE2MmY5MmZmNjMyYSIsImludGVybmFsX3NlY3JldCI6ImE3NjcyMzA4LTkyYWUtNDBhMC1iZjhlLTRiOWJiMGFhN2MwNSJ9.4wvpYDGU3A-6-UkVbx8RYeT3-PViDkjbjHR4IA_IIxM"
JWT_SECRET= "secret"